### ISSUE TITLE
protobuf issue

### ISSUE THREAD

**Issue by FocSon** [Glacier-Luo/crescentjs#1]
Hello, the protobuf issue mentioned in the readme seems to be resolved.

I've placed some limit and market order and i had no issue without the patch.
You'll maybe need some more testing to confirm that.

Also i would like to make a little tip but seems like your address hasn't made any tx for a while, i wanted to make sure that you havn't loose your keys.

Thanks for your work.

**Comment by Glacier-Luo** [comment]
Hello, could you please show me how you use my project? I've done some testing, and the protobuf problem still exists, even if cosmjs is updated to the latest version.

My wallet is still safe and I haven't traded on crescent for a long time.
The collapse of luna caused great damage to crescent. I don't seem to have anything worth doing on crescent after that. 
Or do you have any suggestions?

**Comment by FocSon** [comment]
```js
export async function swapCrescent(denomToSwap, denomToGet, nativeDenom, amount) {
    amount = amount * 10**decimals[denomToSwap];
    const usedPair = crescentPairs[denomToSwap][denomToGet];

    const limitOrder = {
        typeUrl: '/crescent.liquidity.v1beta1.MsgMarketOrder',
        value: {
            orderer: addresses[crescentChainId],
            pairId: usedPair.id,
            direction: 2,
            offerCoin: {
                denom: denomToSwap,
                amount: `${amount}`
            },
            demandCoinDenom: denomToGet,
            amount: `${amount}`,
            orderLifespans: "0s"
        }
    };

    await stargateClient[crescentChainId].signAndBroadcast(addresses[crescentChainId], [limitOrder], fees[crescentChainId]);

    return await waitForBalance(crescentChainId, denomToGet) / 10 ** decimals[nativeDenom];
}
```

Here is my implementation of a market order.
Amount is a value like '100000' for 0.1 $ATOM for exemple.

Could you give me any clue about what is the problem with protobuf ? When does the problem occur ?
I would be glad to make some testings by my side.

Ok, i'll look forward for the tip when i'll be able to.
Luna was a hard time for all of us, hope it didn't affect you too much..

**Comment by Glacier-Luo** [comment]
Thank you very much!
I've solved this bug, there is a mistake about variable type in the `index.js`. 
I submitted a new commit:https://github.com/Glacier-Luo/crescentjs/commit/e65f6b3a14d1b30f8381623b1ea4386e547b3dee

**Comment by FocSon** [comment]
Ok, i'll close the issue then, congratulations 😄
